// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetPrintJobParams is parameters of getPrintJob operation.
type GetPrintJobParams struct {
	JobID string
}

func unpackGetPrintJobParams(packed middleware.Parameters) (params GetPrintJobParams) {
	{
		key := middleware.ParameterKey{
			Name: "job_id",
			In:   "path",
		}
		params.JobID = packed[key].(string)
	}
	return params
}

func decodeGetPrintJobParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPrintJobParams, _ error) {
	// Decode path: job_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "job_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.JobID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "job_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPrinterStatusParams is parameters of getPrinterStatus operation.
type GetPrinterStatusParams struct {
	PrinterID string
}

func unpackGetPrinterStatusParams(packed middleware.Parameters) (params GetPrinterStatusParams) {
	{
		key := middleware.ParameterKey{
			Name: "printer_id",
			In:   "path",
		}
		params.PrinterID = packed[key].(string)
	}
	return params
}

func decodeGetPrinterStatusParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPrinterStatusParams, _ error) {
	// Decode path: printer_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "printer_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.PrinterID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "printer_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
