// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetPrintJob implements getPrintJob operation.
//
// Get the current or terminal CUPS status of a print job.
//
// GET /jobs/{job_id}
func (UnimplementedHandler) GetPrintJob(ctx context.Context, params GetPrintJobParams) (r *PrintJobState, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPrinterStatus implements getPrinterStatus operation.
//
// Get the current CUPS state for a configured printer.
//
// GET /printers/{printer_id}/status
func (UnimplementedHandler) GetPrinterStatus(ctx context.Context, params GetPrinterStatusParams) (r *PrinterStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthCheck implements healthCheck operation.
//
// Check whether the API process is healthy.
//
// GET /healthz
func (UnimplementedHandler) HealthCheck(ctx context.Context) (r *HealthStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPresets implements listPresets operation.
//
// List configured print presets.
//
// GET /presets
func (UnimplementedHandler) ListPresets(ctx context.Context) (r *PrintPresetList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPrinters implements listPrinters operation.
//
// List configured printers and their declared capabilities.
//
// GET /printers
func (UnimplementedHandler) ListPrinters(ctx context.Context) (r *PrinterList, _ error) {
	return r, ht.ErrNotImplemented
}

// PrintDocument implements printDocument operation.
//
// Queue a PDF document for printing.
//
// POST /print
func (UnimplementedHandler) PrintDocument(ctx context.Context, req *PrintDocumentReq) (r PrintDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}
