// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetPrintJobOperation      OperationName = "GetPrintJob"
	GetPrinterStatusOperation OperationName = "GetPrinterStatus"
	HealthCheckOperation      OperationName = "HealthCheck"
	ListPresetsOperation      OperationName = "ListPresets"
	ListPrintersOperation     OperationName = "ListPrinters"
	PrintDocumentOperation    OperationName = "PrintDocument"
)
