// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"mime"
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

func (s *Server) decodePrintDocumentRequest(r *http.Request) (
	req *PrintDocumentReq,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	var closers []func() error
	close = func() error {
		var merr error
		// Close in reverse order, to match defer behavior.
		for i := len(closers) - 1; i >= 0; i-- {
			c := closers[i]
			merr = errors.Join(merr, c())
		}
		return merr
	}
	defer func() {
		if rerr != nil {
			rerr = errors.Join(rerr, close())
		}
	}()
	ct, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil {
		return req, rawBody, close, errors.Wrap(err, "parse media type")
	}
	switch {
	case ct == "multipart/form-data":
		if r.ContentLength == 0 {
			return req, rawBody, close, validate.ErrBodyRequired
		}
		if err := r.ParseMultipartForm(s.cfg.MaxMultipartMemory); err != nil {
			return req, rawBody, close, errors.Wrap(err, "parse multipart form")
		}
		// Remove all temporary files created by ParseMultipartForm when the request is done.
		//
		// Notice that the closers are called in reverse order, to match defer behavior, so
		// any opened file will be closed before RemoveAll call.
		closers = append(closers, r.MultipartForm.RemoveAll)
		// Form values may be unused.
		form := url.Values(r.MultipartForm.Value)
		_ = form

		var request PrintDocumentReq
		q := uri.NewQueryDecoder(form)
		{
			cfg := uri.QueryParameterDecodingConfig{
				Name:    "printer_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.HasParam(cfg); err == nil {
				if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
					var requestDotPrinterIDVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						requestDotPrinterIDVal = c
						return nil
					}(); err != nil {
						return err
					}
					request.PrinterID.SetTo(requestDotPrinterIDVal)
					return nil
				}); err != nil {
					return req, rawBody, close, errors.Wrap(err, "decode \"printer_id\"")
				}
			}
		}
		{
			cfg := uri.QueryParameterDecodingConfig{
				Name:    "preset",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.HasParam(cfg); err == nil {
				if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
					var requestDotPresetVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						requestDotPresetVal = c
						return nil
					}(); err != nil {
						return err
					}
					request.Preset.SetTo(requestDotPresetVal)
					return nil
				}); err != nil {
					return req, rawBody, close, errors.Wrap(err, "decode \"preset\"")
				}
			}
		}
		{
			cfg := uri.QueryParameterDecodingConfig{
				Name:    "copies",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.HasParam(cfg); err == nil {
				if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
					var requestDotCopiesVal int
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToInt(val)
						if err != nil {
							return err
						}

						requestDotCopiesVal = c
						return nil
					}(); err != nil {
						return err
					}
					request.Copies.SetTo(requestDotCopiesVal)
					return nil
				}); err != nil {
					return req, rawBody, close, errors.Wrap(err, "decode \"copies\"")
				}
				if err := func() error {
					if value, ok := request.Copies.Get(); ok {
						if err := func() error {
							if err := (validate.Int{
								MinSet:        true,
								Min:           1,
								MaxSet:        true,
								Max:           99,
								MinExclusive:  false,
								MaxExclusive:  false,
								MultipleOfSet: false,
								MultipleOf:    0,
								Pattern:       nil,
							}).Validate(int64(value)); err != nil {
								return errors.Wrap(err, "int")
							}
							return nil
						}(); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return req, rawBody, close, errors.Wrap(err, "validate")
				}
			}
		}
		{
			cfg := uri.QueryParameterDecodingConfig{
				Name:    "duplex",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.HasParam(cfg); err == nil {
				if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
					var requestDotDuplexVal DuplexMode
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						requestDotDuplexVal = DuplexMode(c)
						return nil
					}(); err != nil {
						return err
					}
					request.Duplex.SetTo(requestDotDuplexVal)
					return nil
				}); err != nil {
					return req, rawBody, close, errors.Wrap(err, "decode \"duplex\"")
				}
				if err := func() error {
					if value, ok := request.Duplex.Get(); ok {
						if err := func() error {
							if err := value.Validate(); err != nil {
								return err
							}
							return nil
						}(); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return req, rawBody, close, errors.Wrap(err, "validate")
				}
			}
		}
		{
			cfg := uri.QueryParameterDecodingConfig{
				Name:    "color_mode",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.HasParam(cfg); err == nil {
				if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
					var requestDotColorModeVal ColorMode
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						requestDotColorModeVal = ColorMode(c)
						return nil
					}(); err != nil {
						return err
					}
					request.ColorMode.SetTo(requestDotColorModeVal)
					return nil
				}); err != nil {
					return req, rawBody, close, errors.Wrap(err, "decode \"color_mode\"")
				}
				if err := func() error {
					if value, ok := request.ColorMode.Get(); ok {
						if err := func() error {
							if err := value.Validate(); err != nil {
								return err
							}
							return nil
						}(); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return req, rawBody, close, errors.Wrap(err, "validate")
				}
			}
		}
		{
			cfg := uri.QueryParameterDecodingConfig{
				Name:    "media",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.HasParam(cfg); err == nil {
				if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
					var requestDotMediaVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						requestDotMediaVal = c
						return nil
					}(); err != nil {
						return err
					}
					request.Media.SetTo(requestDotMediaVal)
					return nil
				}); err != nil {
					return req, rawBody, close, errors.Wrap(err, "decode \"media\"")
				}
			}
		}
		{
			cfg := uri.QueryParameterDecodingConfig{
				Name:    "scaling",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.HasParam(cfg); err == nil {
				if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
					var requestDotScalingVal ScalingMode
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						requestDotScalingVal = ScalingMode(c)
						return nil
					}(); err != nil {
						return err
					}
					request.Scaling.SetTo(requestDotScalingVal)
					return nil
				}); err != nil {
					return req, rawBody, close, errors.Wrap(err, "decode \"scaling\"")
				}
				if err := func() error {
					if value, ok := request.Scaling.Get(); ok {
						if err := func() error {
							if err := value.Validate(); err != nil {
								return err
							}
							return nil
						}(); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return req, rawBody, close, errors.Wrap(err, "validate")
				}
			}
		}
		{
			cfg := uri.QueryParameterDecodingConfig{
				Name:    "edge_to_edge",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.HasParam(cfg); err == nil {
				if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
					var requestDotEdgeToEdgeVal bool
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToBool(val)
						if err != nil {
							return err
						}

						requestDotEdgeToEdgeVal = c
						return nil
					}(); err != nil {
						return err
					}
					request.EdgeToEdge.SetTo(requestDotEdgeToEdgeVal)
					return nil
				}); err != nil {
					return req, rawBody, close, errors.Wrap(err, "decode \"edge_to_edge\"")
				}
			}
		}
		{
			if err := func() error {
				files, ok := r.MultipartForm.File["file"]
				if !ok || len(files) < 1 {
					return validate.ErrFieldRequired
				}
				fh := files[0]

				f, err := fh.Open()
				if err != nil {
					return errors.Wrap(err, "open")
				}
				closers = append(closers, f.Close)
				request.File = ht.MultipartFile{
					Name:   fh.Filename,
					File:   f,
					Size:   fh.Size,
					Header: fh.Header,
				}
				return nil
			}(); err != nil {
				return req, rawBody, close, errors.Wrap(err, "decode \"file\"")
			}
		}
		return &request, rawBody, close, nil
	default:
		return req, rawBody, close, validate.InvalidContentType(ct)
	}
}
