// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetPrintJob implements getPrintJob operation.
	//
	// Get the current or terminal CUPS status of a print job.
	//
	// GET /jobs/{job_id}
	GetPrintJob(ctx context.Context, params GetPrintJobParams) (*PrintJobState, error)
	// GetPrinterStatus implements getPrinterStatus operation.
	//
	// Get the current CUPS state for a configured printer.
	//
	// GET /printers/{printer_id}/status
	GetPrinterStatus(ctx context.Context, params GetPrinterStatusParams) (*PrinterStatus, error)
	// HealthCheck implements healthCheck operation.
	//
	// Check whether the API process is healthy.
	//
	// GET /healthz
	HealthCheck(ctx context.Context) (*HealthStatus, error)
	// ListPresets implements listPresets operation.
	//
	// List configured print presets.
	//
	// GET /presets
	ListPresets(ctx context.Context) (*PrintPresetList, error)
	// ListPrinters implements listPrinters operation.
	//
	// List configured printers and their declared capabilities.
	//
	// GET /printers
	ListPrinters(ctx context.Context) (*PrinterList, error)
	// PrintDocument implements printDocument operation.
	//
	// Queue a PDF document for printing.
	//
	// POST /print
	PrintDocument(ctx context.Context, req *PrintDocumentReq) (PrintDocumentRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
