// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"github.com/go-faster/errors"
	ht "github.com/ogen-go/ogen/http"
)

type ApiKeyAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *ApiKeyAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *ApiKeyAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKeyAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *ApiKeyAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ColorMode
type ColorMode string

const (
	ColorModeAuto       ColorMode = "auto"
	ColorModeColor      ColorMode = "color"
	ColorModeMonochrome ColorMode = "monochrome"
)

// AllValues returns all ColorMode values.
func (ColorMode) AllValues() []ColorMode {
	return []ColorMode{
		ColorModeAuto,
		ColorModeColor,
		ColorModeMonochrome,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ColorMode) MarshalText() ([]byte, error) {
	switch s {
	case ColorModeAuto:
		return []byte(s), nil
	case ColorModeColor:
		return []byte(s), nil
	case ColorModeMonochrome:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ColorMode) UnmarshalText(data []byte) error {
	switch ColorMode(data) {
	case ColorModeAuto:
		*s = ColorModeAuto
		return nil
	case ColorModeColor:
		*s = ColorModeColor
		return nil
	case ColorModeMonochrome:
		*s = ColorModeMonochrome
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/DuplexMode
type DuplexMode string

const (
	DuplexModeNone      DuplexMode = "none"
	DuplexModeLongEdge  DuplexMode = "long-edge"
	DuplexModeShortEdge DuplexMode = "short-edge"
)

// AllValues returns all DuplexMode values.
func (DuplexMode) AllValues() []DuplexMode {
	return []DuplexMode{
		DuplexModeNone,
		DuplexModeLongEdge,
		DuplexModeShortEdge,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DuplexMode) MarshalText() ([]byte, error) {
	switch s {
	case DuplexModeNone:
		return []byte(s), nil
	case DuplexModeLongEdge:
		return []byte(s), nil
	case DuplexModeShortEdge:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DuplexMode) UnmarshalText(data []byte) error {
	switch DuplexMode(data) {
	case DuplexModeNone:
		*s = DuplexModeNone
		return nil
	case DuplexModeLongEdge:
		*s = DuplexModeLongEdge
		return nil
	case DuplexModeShortEdge:
		*s = DuplexModeShortEdge
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Printable-area minimizes driver-added margins but still respects the hardware unprintable area;
// full-bleed means the printer and media support printing to the physical edge.
// Ref: #/components/schemas/EdgeToEdgeCapability
type EdgeToEdgeCapability string

const (
	EdgeToEdgeCapabilityUnsupported   EdgeToEdgeCapability = "unsupported"
	EdgeToEdgeCapabilityPrintableArea EdgeToEdgeCapability = "printable-area"
	EdgeToEdgeCapabilityFullBleed     EdgeToEdgeCapability = "full-bleed"
)

// AllValues returns all EdgeToEdgeCapability values.
func (EdgeToEdgeCapability) AllValues() []EdgeToEdgeCapability {
	return []EdgeToEdgeCapability{
		EdgeToEdgeCapabilityUnsupported,
		EdgeToEdgeCapabilityPrintableArea,
		EdgeToEdgeCapabilityFullBleed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EdgeToEdgeCapability) MarshalText() ([]byte, error) {
	switch s {
	case EdgeToEdgeCapabilityUnsupported:
		return []byte(s), nil
	case EdgeToEdgeCapabilityPrintableArea:
		return []byte(s), nil
	case EdgeToEdgeCapabilityFullBleed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EdgeToEdgeCapability) UnmarshalText(data []byte) error {
	switch EdgeToEdgeCapability(data) {
	case EdgeToEdgeCapabilityUnsupported:
		*s = EdgeToEdgeCapabilityUnsupported
		return nil
	case EdgeToEdgeCapabilityPrintableArea:
		*s = EdgeToEdgeCapabilityPrintableArea
		return nil
	case EdgeToEdgeCapabilityFullBleed:
		*s = EdgeToEdgeCapabilityFullBleed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/HealthStatus
type HealthStatus struct {
	Status HealthStatusStatus `json:"status"`
}

// GetStatus returns the value of Status.
func (s *HealthStatus) GetStatus() HealthStatusStatus {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *HealthStatus) SetStatus(val HealthStatusStatus) {
	s.Status = val
}

type HealthStatusStatus string

const (
	HealthStatusStatusOk HealthStatusStatus = "ok"
)

// AllValues returns all HealthStatusStatus values.
func (HealthStatusStatus) AllValues() []HealthStatusStatus {
	return []HealthStatusStatus{
		HealthStatusStatusOk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatusStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusStatusOk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatusStatus) UnmarshalText(data []byte) error {
	switch HealthStatusStatus(data) {
	case HealthStatusStatusOk:
		*s = HealthStatusStatusOk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptColorMode returns new OptColorMode with value set to v.
func NewOptColorMode(v ColorMode) OptColorMode {
	return OptColorMode{
		Value: v,
		Set:   true,
	}
}

// OptColorMode is optional ColorMode.
type OptColorMode struct {
	Value ColorMode
	Set   bool
}

// IsSet returns true if OptColorMode was set.
func (o OptColorMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptColorMode) Reset() {
	var v ColorMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptColorMode) SetTo(v ColorMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptColorMode) Get() (v ColorMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptColorMode) Or(d ColorMode) ColorMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDuplexMode returns new OptDuplexMode with value set to v.
func NewOptDuplexMode(v DuplexMode) OptDuplexMode {
	return OptDuplexMode{
		Value: v,
		Set:   true,
	}
}

// OptDuplexMode is optional DuplexMode.
type OptDuplexMode struct {
	Value DuplexMode
	Set   bool
}

// IsSet returns true if OptDuplexMode was set.
func (o OptDuplexMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDuplexMode) Reset() {
	var v DuplexMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDuplexMode) SetTo(v DuplexMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDuplexMode) Get() (v DuplexMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDuplexMode) Or(d DuplexMode) DuplexMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptScalingMode returns new OptScalingMode with value set to v.
func NewOptScalingMode(v ScalingMode) OptScalingMode {
	return OptScalingMode{
		Value: v,
		Set:   true,
	}
}

// OptScalingMode is optional ScalingMode.
type OptScalingMode struct {
	Value ScalingMode
	Set   bool
}

// IsSet returns true if OptScalingMode was set.
func (o OptScalingMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptScalingMode) Reset() {
	var v ScalingMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptScalingMode) SetTo(v ScalingMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptScalingMode) Get() (v ScalingMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptScalingMode) Or(d ScalingMode) ScalingMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PrintDocumentBadRequest Error

func (*PrintDocumentBadRequest) printDocumentRes() {}

type PrintDocumentInternalServerError Error

func (*PrintDocumentInternalServerError) printDocumentRes() {}

type PrintDocumentReq struct {
	// PDF document to print.
	File ht.MultipartFile `json:"file"`
	// Configured printer ID. The default printer is used when omitted.
	PrinterID OptString `json:"printer_id"`
	// Configured print preset. Explicit request fields override preset values.
	Preset    OptString     `json:"preset"`
	Copies    OptInt        `json:"copies"`
	Duplex    OptDuplexMode `json:"duplex"`
	ColorMode OptColorMode  `json:"color_mode"`
	// Media name declared by the selected printer, such as a4 or letter.
	Media   OptString      `json:"media"`
	Scaling OptScalingMode `json:"scaling"`
	// Minimize driver-added margins. This does not imply scaling or physical full-bleed support; use
	// scaling to control document resizing explicitly.
	EdgeToEdge OptBool `json:"edge_to_edge"`
}

// GetFile returns the value of File.
func (s *PrintDocumentReq) GetFile() ht.MultipartFile {
	return s.File
}

// GetPrinterID returns the value of PrinterID.
func (s *PrintDocumentReq) GetPrinterID() OptString {
	return s.PrinterID
}

// GetPreset returns the value of Preset.
func (s *PrintDocumentReq) GetPreset() OptString {
	return s.Preset
}

// GetCopies returns the value of Copies.
func (s *PrintDocumentReq) GetCopies() OptInt {
	return s.Copies
}

// GetDuplex returns the value of Duplex.
func (s *PrintDocumentReq) GetDuplex() OptDuplexMode {
	return s.Duplex
}

// GetColorMode returns the value of ColorMode.
func (s *PrintDocumentReq) GetColorMode() OptColorMode {
	return s.ColorMode
}

// GetMedia returns the value of Media.
func (s *PrintDocumentReq) GetMedia() OptString {
	return s.Media
}

// GetScaling returns the value of Scaling.
func (s *PrintDocumentReq) GetScaling() OptScalingMode {
	return s.Scaling
}

// GetEdgeToEdge returns the value of EdgeToEdge.
func (s *PrintDocumentReq) GetEdgeToEdge() OptBool {
	return s.EdgeToEdge
}

// SetFile sets the value of File.
func (s *PrintDocumentReq) SetFile(val ht.MultipartFile) {
	s.File = val
}

// SetPrinterID sets the value of PrinterID.
func (s *PrintDocumentReq) SetPrinterID(val OptString) {
	s.PrinterID = val
}

// SetPreset sets the value of Preset.
func (s *PrintDocumentReq) SetPreset(val OptString) {
	s.Preset = val
}

// SetCopies sets the value of Copies.
func (s *PrintDocumentReq) SetCopies(val OptInt) {
	s.Copies = val
}

// SetDuplex sets the value of Duplex.
func (s *PrintDocumentReq) SetDuplex(val OptDuplexMode) {
	s.Duplex = val
}

// SetColorMode sets the value of ColorMode.
func (s *PrintDocumentReq) SetColorMode(val OptColorMode) {
	s.ColorMode = val
}

// SetMedia sets the value of Media.
func (s *PrintDocumentReq) SetMedia(val OptString) {
	s.Media = val
}

// SetScaling sets the value of Scaling.
func (s *PrintDocumentReq) SetScaling(val OptScalingMode) {
	s.Scaling = val
}

// SetEdgeToEdge sets the value of EdgeToEdge.
func (s *PrintDocumentReq) SetEdgeToEdge(val OptBool) {
	s.EdgeToEdge = val
}

type PrintDocumentRequestEntityTooLarge Error

func (*PrintDocumentRequestEntityTooLarge) printDocumentRes() {}

// Ref: #/components/schemas/PrintJob
type PrintJob struct {
	JobID     string         `json:"job_id"`
	PrinterID string         `json:"printer_id"`
	Status    PrintJobStatus `json:"status"`
}

// GetJobID returns the value of JobID.
func (s *PrintJob) GetJobID() string {
	return s.JobID
}

// GetPrinterID returns the value of PrinterID.
func (s *PrintJob) GetPrinterID() string {
	return s.PrinterID
}

// GetStatus returns the value of Status.
func (s *PrintJob) GetStatus() PrintJobStatus {
	return s.Status
}

// SetJobID sets the value of JobID.
func (s *PrintJob) SetJobID(val string) {
	s.JobID = val
}

// SetPrinterID sets the value of PrinterID.
func (s *PrintJob) SetPrinterID(val string) {
	s.PrinterID = val
}

// SetStatus sets the value of Status.
func (s *PrintJob) SetStatus(val PrintJobStatus) {
	s.Status = val
}

func (*PrintJob) printDocumentRes() {}

// Ref: #/components/schemas/PrintJobState
type PrintJobState struct {
	JobID string `json:"job_id"`
	// Configured printer ID when the job ID belongs to one.
	PrinterID OptString           `json:"printer_id"`
	Status    PrintJobStateStatus `json:"status"`
	Message   OptString           `json:"message"`
}

// GetJobID returns the value of JobID.
func (s *PrintJobState) GetJobID() string {
	return s.JobID
}

// GetPrinterID returns the value of PrinterID.
func (s *PrintJobState) GetPrinterID() OptString {
	return s.PrinterID
}

// GetStatus returns the value of Status.
func (s *PrintJobState) GetStatus() PrintJobStateStatus {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *PrintJobState) GetMessage() OptString {
	return s.Message
}

// SetJobID sets the value of JobID.
func (s *PrintJobState) SetJobID(val string) {
	s.JobID = val
}

// SetPrinterID sets the value of PrinterID.
func (s *PrintJobState) SetPrinterID(val OptString) {
	s.PrinterID = val
}

// SetStatus sets the value of Status.
func (s *PrintJobState) SetStatus(val PrintJobStateStatus) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *PrintJobState) SetMessage(val OptString) {
	s.Message = val
}

type PrintJobStateStatus string

const (
	PrintJobStateStatusQueued     PrintJobStateStatus = "queued"
	PrintJobStateStatusProcessing PrintJobStateStatus = "processing"
	PrintJobStateStatusCompleted  PrintJobStateStatus = "completed"
	PrintJobStateStatusCanceled   PrintJobStateStatus = "canceled"
	PrintJobStateStatusAborted    PrintJobStateStatus = "aborted"
	PrintJobStateStatusUnknown    PrintJobStateStatus = "unknown"
)

// AllValues returns all PrintJobStateStatus values.
func (PrintJobStateStatus) AllValues() []PrintJobStateStatus {
	return []PrintJobStateStatus{
		PrintJobStateStatusQueued,
		PrintJobStateStatusProcessing,
		PrintJobStateStatusCompleted,
		PrintJobStateStatusCanceled,
		PrintJobStateStatusAborted,
		PrintJobStateStatusUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PrintJobStateStatus) MarshalText() ([]byte, error) {
	switch s {
	case PrintJobStateStatusQueued:
		return []byte(s), nil
	case PrintJobStateStatusProcessing:
		return []byte(s), nil
	case PrintJobStateStatusCompleted:
		return []byte(s), nil
	case PrintJobStateStatusCanceled:
		return []byte(s), nil
	case PrintJobStateStatusAborted:
		return []byte(s), nil
	case PrintJobStateStatusUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PrintJobStateStatus) UnmarshalText(data []byte) error {
	switch PrintJobStateStatus(data) {
	case PrintJobStateStatusQueued:
		*s = PrintJobStateStatusQueued
		return nil
	case PrintJobStateStatusProcessing:
		*s = PrintJobStateStatusProcessing
		return nil
	case PrintJobStateStatusCompleted:
		*s = PrintJobStateStatusCompleted
		return nil
	case PrintJobStateStatusCanceled:
		*s = PrintJobStateStatusCanceled
		return nil
	case PrintJobStateStatusAborted:
		*s = PrintJobStateStatusAborted
		return nil
	case PrintJobStateStatusUnknown:
		*s = PrintJobStateStatusUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type PrintJobStatus string

const (
	PrintJobStatusQueued PrintJobStatus = "queued"
)

// AllValues returns all PrintJobStatus values.
func (PrintJobStatus) AllValues() []PrintJobStatus {
	return []PrintJobStatus{
		PrintJobStatusQueued,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PrintJobStatus) MarshalText() ([]byte, error) {
	switch s {
	case PrintJobStatusQueued:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PrintJobStatus) UnmarshalText(data []byte) error {
	switch PrintJobStatus(data) {
	case PrintJobStatusQueued:
		*s = PrintJobStatusQueued
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/PrintPreset
type PrintPreset struct {
	ID         string         `json:"id"`
	PrinterID  OptString      `json:"printer_id"`
	Copies     OptInt         `json:"copies"`
	Duplex     OptDuplexMode  `json:"duplex"`
	ColorMode  OptColorMode   `json:"color_mode"`
	Media      OptString      `json:"media"`
	Scaling    OptScalingMode `json:"scaling"`
	EdgeToEdge OptBool        `json:"edge_to_edge"`
}

// GetID returns the value of ID.
func (s *PrintPreset) GetID() string {
	return s.ID
}

// GetPrinterID returns the value of PrinterID.
func (s *PrintPreset) GetPrinterID() OptString {
	return s.PrinterID
}

// GetCopies returns the value of Copies.
func (s *PrintPreset) GetCopies() OptInt {
	return s.Copies
}

// GetDuplex returns the value of Duplex.
func (s *PrintPreset) GetDuplex() OptDuplexMode {
	return s.Duplex
}

// GetColorMode returns the value of ColorMode.
func (s *PrintPreset) GetColorMode() OptColorMode {
	return s.ColorMode
}

// GetMedia returns the value of Media.
func (s *PrintPreset) GetMedia() OptString {
	return s.Media
}

// GetScaling returns the value of Scaling.
func (s *PrintPreset) GetScaling() OptScalingMode {
	return s.Scaling
}

// GetEdgeToEdge returns the value of EdgeToEdge.
func (s *PrintPreset) GetEdgeToEdge() OptBool {
	return s.EdgeToEdge
}

// SetID sets the value of ID.
func (s *PrintPreset) SetID(val string) {
	s.ID = val
}

// SetPrinterID sets the value of PrinterID.
func (s *PrintPreset) SetPrinterID(val OptString) {
	s.PrinterID = val
}

// SetCopies sets the value of Copies.
func (s *PrintPreset) SetCopies(val OptInt) {
	s.Copies = val
}

// SetDuplex sets the value of Duplex.
func (s *PrintPreset) SetDuplex(val OptDuplexMode) {
	s.Duplex = val
}

// SetColorMode sets the value of ColorMode.
func (s *PrintPreset) SetColorMode(val OptColorMode) {
	s.ColorMode = val
}

// SetMedia sets the value of Media.
func (s *PrintPreset) SetMedia(val OptString) {
	s.Media = val
}

// SetScaling sets the value of Scaling.
func (s *PrintPreset) SetScaling(val OptScalingMode) {
	s.Scaling = val
}

// SetEdgeToEdge sets the value of EdgeToEdge.
func (s *PrintPreset) SetEdgeToEdge(val OptBool) {
	s.EdgeToEdge = val
}

// Ref: #/components/schemas/PrintPresetList
type PrintPresetList struct {
	Presets []PrintPreset `json:"presets"`
}

// GetPresets returns the value of Presets.
func (s *PrintPresetList) GetPresets() []PrintPreset {
	return s.Presets
}

// SetPresets sets the value of Presets.
func (s *PrintPresetList) SetPresets(val []PrintPreset) {
	s.Presets = val
}

// Ref: #/components/schemas/Printer
type Printer struct {
	ID           string              `json:"id"`
	DisplayName  string              `json:"display_name"`
	Default      bool                `json:"default"`
	Capabilities PrinterCapabilities `json:"capabilities"`
}

// GetID returns the value of ID.
func (s *Printer) GetID() string {
	return s.ID
}

// GetDisplayName returns the value of DisplayName.
func (s *Printer) GetDisplayName() string {
	return s.DisplayName
}

// GetDefault returns the value of Default.
func (s *Printer) GetDefault() bool {
	return s.Default
}

// GetCapabilities returns the value of Capabilities.
func (s *Printer) GetCapabilities() PrinterCapabilities {
	return s.Capabilities
}

// SetID sets the value of ID.
func (s *Printer) SetID(val string) {
	s.ID = val
}

// SetDisplayName sets the value of DisplayName.
func (s *Printer) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetDefault sets the value of Default.
func (s *Printer) SetDefault(val bool) {
	s.Default = val
}

// SetCapabilities sets the value of Capabilities.
func (s *Printer) SetCapabilities(val PrinterCapabilities) {
	s.Capabilities = val
}

// Ref: #/components/schemas/PrinterCapabilities
type PrinterCapabilities struct {
	ColorModes   []ColorMode          `json:"color_modes"`
	DuplexModes  []DuplexMode         `json:"duplex_modes"`
	Media        []string             `json:"media"`
	ScalingModes []ScalingMode        `json:"scaling_modes"`
	EdgeToEdge   EdgeToEdgeCapability `json:"edge_to_edge"`
	MaxCopies    int                  `json:"max_copies"`
}

// GetColorModes returns the value of ColorModes.
func (s *PrinterCapabilities) GetColorModes() []ColorMode {
	return s.ColorModes
}

// GetDuplexModes returns the value of DuplexModes.
func (s *PrinterCapabilities) GetDuplexModes() []DuplexMode {
	return s.DuplexModes
}

// GetMedia returns the value of Media.
func (s *PrinterCapabilities) GetMedia() []string {
	return s.Media
}

// GetScalingModes returns the value of ScalingModes.
func (s *PrinterCapabilities) GetScalingModes() []ScalingMode {
	return s.ScalingModes
}

// GetEdgeToEdge returns the value of EdgeToEdge.
func (s *PrinterCapabilities) GetEdgeToEdge() EdgeToEdgeCapability {
	return s.EdgeToEdge
}

// GetMaxCopies returns the value of MaxCopies.
func (s *PrinterCapabilities) GetMaxCopies() int {
	return s.MaxCopies
}

// SetColorModes sets the value of ColorModes.
func (s *PrinterCapabilities) SetColorModes(val []ColorMode) {
	s.ColorModes = val
}

// SetDuplexModes sets the value of DuplexModes.
func (s *PrinterCapabilities) SetDuplexModes(val []DuplexMode) {
	s.DuplexModes = val
}

// SetMedia sets the value of Media.
func (s *PrinterCapabilities) SetMedia(val []string) {
	s.Media = val
}

// SetScalingModes sets the value of ScalingModes.
func (s *PrinterCapabilities) SetScalingModes(val []ScalingMode) {
	s.ScalingModes = val
}

// SetEdgeToEdge sets the value of EdgeToEdge.
func (s *PrinterCapabilities) SetEdgeToEdge(val EdgeToEdgeCapability) {
	s.EdgeToEdge = val
}

// SetMaxCopies sets the value of MaxCopies.
func (s *PrinterCapabilities) SetMaxCopies(val int) {
	s.MaxCopies = val
}

// Ref: #/components/schemas/PrinterList
type PrinterList struct {
	Printers []Printer `json:"printers"`
}

// GetPrinters returns the value of Printers.
func (s *PrinterList) GetPrinters() []Printer {
	return s.Printers
}

// SetPrinters sets the value of Printers.
func (s *PrinterList) SetPrinters(val []Printer) {
	s.Printers = val
}

// Ref: #/components/schemas/PrinterStatus
type PrinterStatus struct {
	PrinterID string              `json:"printer_id"`
	Status    PrinterStatusStatus `json:"status"`
	Message   OptString           `json:"message"`
}

// GetPrinterID returns the value of PrinterID.
func (s *PrinterStatus) GetPrinterID() string {
	return s.PrinterID
}

// GetStatus returns the value of Status.
func (s *PrinterStatus) GetStatus() PrinterStatusStatus {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *PrinterStatus) GetMessage() OptString {
	return s.Message
}

// SetPrinterID sets the value of PrinterID.
func (s *PrinterStatus) SetPrinterID(val string) {
	s.PrinterID = val
}

// SetStatus sets the value of Status.
func (s *PrinterStatus) SetStatus(val PrinterStatusStatus) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *PrinterStatus) SetMessage(val OptString) {
	s.Message = val
}

type PrinterStatusStatus string

const (
	PrinterStatusStatusReady       PrinterStatusStatus = "ready"
	PrinterStatusStatusBusy        PrinterStatusStatus = "busy"
	PrinterStatusStatusUnavailable PrinterStatusStatus = "unavailable"
	PrinterStatusStatusUnknown     PrinterStatusStatus = "unknown"
)

// AllValues returns all PrinterStatusStatus values.
func (PrinterStatusStatus) AllValues() []PrinterStatusStatus {
	return []PrinterStatusStatus{
		PrinterStatusStatusReady,
		PrinterStatusStatusBusy,
		PrinterStatusStatusUnavailable,
		PrinterStatusStatusUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PrinterStatusStatus) MarshalText() ([]byte, error) {
	switch s {
	case PrinterStatusStatusReady:
		return []byte(s), nil
	case PrinterStatusStatusBusy:
		return []byte(s), nil
	case PrinterStatusStatusUnavailable:
		return []byte(s), nil
	case PrinterStatusStatusUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PrinterStatusStatus) UnmarshalText(data []byte) error {
	switch PrinterStatusStatus(data) {
	case PrinterStatusStatusReady:
		*s = PrinterStatusStatusReady
		return nil
	case PrinterStatusStatusBusy:
		*s = PrinterStatusStatusBusy
		return nil
	case PrinterStatusStatusUnavailable:
		*s = PrinterStatusStatusUnavailable
		return nil
	case PrinterStatusStatusUnknown:
		*s = PrinterStatusStatusUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Auto uses the printer default, none preserves physical document size, fit shows the whole document,
// and fill covers the media while potentially cropping edges.
// Ref: #/components/schemas/ScalingMode
type ScalingMode string

const (
	ScalingModeAuto    ScalingMode = "auto"
	ScalingModeAutoFit ScalingMode = "auto-fit"
	ScalingModeFill    ScalingMode = "fill"
	ScalingModeFit     ScalingMode = "fit"
	ScalingModeNone    ScalingMode = "none"
)

// AllValues returns all ScalingMode values.
func (ScalingMode) AllValues() []ScalingMode {
	return []ScalingMode{
		ScalingModeAuto,
		ScalingModeAutoFit,
		ScalingModeFill,
		ScalingModeFit,
		ScalingModeNone,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ScalingMode) MarshalText() ([]byte, error) {
	switch s {
	case ScalingModeAuto:
		return []byte(s), nil
	case ScalingModeAutoFit:
		return []byte(s), nil
	case ScalingModeFill:
		return []byte(s), nil
	case ScalingModeFit:
		return []byte(s), nil
	case ScalingModeNone:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ScalingMode) UnmarshalText(data []byte) error {
	switch ScalingMode(data) {
	case ScalingModeAuto:
		*s = ScalingModeAuto
		return nil
	case ScalingModeAutoFit:
		*s = ScalingModeAutoFit
		return nil
	case ScalingModeFill:
		*s = ScalingModeFill
		return nil
	case ScalingModeFit:
		*s = ScalingModeFit
		return nil
	case ScalingModeNone:
		*s = ScalingModeNone
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
